/// Flutter icons CreditIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CreditIcon
///      fonts:
///       - asset: fonts/CreditIcon.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CreditIcon {
  CreditIcon._();

  static const _kFontFam = 'CreditIcon';

  static const IconData basket = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData credit_card_alt = const IconData(0xf283, fontFamily: _kFontFam);
}
